name: fscl-proc
services: 
  db:
    image: postgres:17
    restart: always 
    environment:
      POSTGRES_HOST: ${DB_HOST}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    networks:
      - server-net
    ports:
      - 5432:5432
    volumes:
      - ../db-data:/var/lib/postgresql/data
networks:
  server-net: {}